// src/features/Rider/types.ts

export type VehicleType = 'BICYCLE' | 'MOTORCYCLE' | 'CAR' | 'VAN';

// Confirm with backend: exact status values for rider verification.
// Mirroring vendor's pattern until confirmed otherwise.
export type RiderStatus = 'PENDING_APPROVAL' | 'APPROVED' | 'REJECTED' | 'SUSPENDED';

export interface RiderProfile {
  id: string;
  userId: string;
  nationalId: string | null; // file URL, generated by backend
  license: string | null; // file URL, generated by backend
  vehicleType: VehicleType;
  vehiclePlate: string;
  vehicleModel: string;
  status: RiderStatus;
  rejectionReason?: string | null;
  suspensionReason?: string | null;
  documentsVerified?: boolean;
  latitude?: number | null;
  longitude?: number | null;
  createdAt: string;
  updatedAt?: string;
}

export interface RiderProfilePayload {
  nationalId?: File;
  license?: File;
  vehicleType: VehicleType;
  vehiclePlate: string;
  vehicleModel: string;
}

export interface RiderLocationPayload {
  latitude: number;
  longitude: number;
}